import { Ubuntu } from 'next/font/google';
import './globals.css';
import PropTypes from "prop-types";

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata = {
  title: 'Next App Starter Template',
  description: "Generated by create next app, modified by Kağan Ahmet Okan. Don't forget to change these.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        {children}
      </body>
    </html>
  );
};

RootLayout.propTypes = {
  children: PropTypes.any,
};